; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
platform = ststm32
framework = arduino

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
upload_protocol = jlink
build_flags =
    -DARDUINO_GENERIC_STM32F103RC
lib_deps =
    stm32duino/STM32duino FreeRTOS
    Adafruit neoPixel
